apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-master-config
  namespace: agent-master
data:
  config.yaml: |
    server:
      port: 3000
      host: 0.0.0.0
      log: info

    redis:
      host: redis.agent-runtime.svc.cluster.local
      port: 6379
      db: 0
      key: agent-runtime:user
      password: ""

    runtime:
      image: build-on-vscode-opencode-image:local
      ttl: 3600
      port: 8080
      workdir: /nas/agent-master/users
      workspacePvcClaimName: agent-master-nas
      workspacePvcSubPathRoot: agent-master/users
      resources:
        requests:
          cpu: 2000m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 2Gi

    init:
      templatesRoot: ./resources/templates

    kubernetes:
      cluster: default
      namespace: agent-runtime
